### ISSUE TITLE
Container: example(s) for long-running operations

### ISSUE THREAD

**Issue by DazWilkin** [googleapis/python-container#3]
Please provide (reference) an example for converting `container_v1.types.Operation` into `api_core.operation.Operation`.

[`create_cluster`](https://googlecloudplatform.github.io/google-cloud-python/latest/_modules/google/cloud/container_v1/gapic/cluster_manager_client.html#ClusterManagerClient.create_cluster) (and other methods in the Cloud Client Library) return (long-running) `Operation`(s).

I assumed (hoped) this would be `google.api_core.operation.Operation` that I could `operation.result()` but, the method turns [`google.cloud.container_v1.types.Operation`](https://googlecloudplatform.github.io/google-cloud-python/latest/container/gapic/v1/types.html#google.cloud.container_v1.types.Operation)

[Spanner's Python Library, for example, [returns](https://googlecloudplatform.github.io/google-cloud-python/latest/spanner/instance-api.html#google.cloud.spanner_v1.instance.Instance.create) google.api_core.operation.Operation in this case]

I'm struggling to connect this with (presumably?) [Long-Running Operations](https://googlecloudplatform.github.io/google-cloud-python/latest/core/operation.html) documented in Core.

I'm unable to new an `OperationsClient`. The Example suggests `operations_v1.OperationsClient()` but this errors with `TypeError: __init__() takes at least 2 arguments (1 given).`

It's unclear what `channel (grpc.Channel)` I should provide.

Is this the correct approach? Having triggered the cluster creation, I'd like to track its progress to completion.

**Comment by busunkim96** [comment]
Waiting to hear back from some ACTools folks who know more about this, but here's what I understand about the situation at the moment.

The generator will add the `google.api_core.operation.Operation` wrapper when the method complies with https://google.aip.dev/151. This API does not, perhaps because it is an older API that was written before the guidelines existed.

The LROs (see [CreateCluster](https://github.com/googleapis/googleapis/blob/f6dd7e47620566925a4b3f1ce029e74e1b2f2516/google/container/v1/cluster_service.proto#L77-L88)) in the service return an [`Operation` message](https://github.com/googleapis/googleapis/blob/f6dd7e47620566925a4b3f1ce029e74e1b2f2516/google/container/v1/cluster_service.proto#L1535-L1552) are defined inside the Container Service.


```
  rpc CreateCluster(CreateClusterRequest) returns (Operation) {
    option (google.api.http) = {
      post: "/v1/{parent=projects/*/locations/*}/clusters"
      body: "*"
      additional_bindings {
        post: "/v1/projects/{project_id}/zones/{zone}/clusters"
        body: "*"
      }
    };
    option (google.api.method_signature) = "project_id,zone,cluster";
    option (google.api.method_signature) = "parent,cluster";
  }
```

Compare this to an API that uses that follows the AIP:

https://github.com/googleapis/googleapis/blob/eabe7c0fde64b1451df6ea171b2009238b0df07c/google/cloud/speech/v1/cloud_speech.proto#L51-L67
```
  rpc LongRunningRecognize(LongRunningRecognizeRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/speech:longrunningrecognize"
      body: "*"
    };
    option (google.api.method_signature) = "config,audio";
    option (google.longrunning.operation_info) = {
      response_type: "LongRunningRecognizeResponse"
      metadata_type: "LongRunningRecognizeMetadata"
    };
  }
```

https://github.com/googleapis/python-speech/blob/b4700a60569cb917f176ae1f504dadac1edb6ae8/google/cloud/speech_v1/services/speech/client.py#L492-L504
